# Imports

In [3]:
import nfl_data_py as nfl
import pandas as pd
import numpy as np

In [12]:
# Pull in weekly injuries

injuries = nfl.import_injuries(range(2009,2025))

In [13]:
# Info check

injuries.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 84684 entries, 0 to 6214
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   season                     84684 non-null  float64
 1   game_type                  84684 non-null  object
 2   team                       84684 non-null  object
 3   week                       84684 non-null  float64
 4   gsis_id                    84684 non-null  object
 5   position                   84684 non-null  object
 6   full_name                  84684 non-null  object
 7   first_name                 84684 non-null  object
 8   last_name                  84684 non-null  object
 9   report_primary_injury      57718 non-null  object
 10  report_secondary_injury    3202 non-null   object
 11  report_status              57724 non-null  object
 12  practice_primary_injury    84462 non-null  object
 13  practice_secondary_injury  4887 non-null   object
 14  practice_status            84684 non-null  object
 15  date_modified              79818 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 11.0+ MB

In [16]:
# Take a look at NaNs in primary injury -- they look to be rest days

injuries[injuries['report_primary_injury'].isna()]

,season,game_type,team,week,gsis_id,position,full_name,first_name,last_name,report_primary_injury,report_secondary_injury,report_status,practice_primary_injury,practice_secondary_injury,practice_status,date_modified
51,2009.0,REG,DET,1.0,00-0021525,TE,Casey Fitzsimmons,Casey,Fitzsimmons,None,None,None,Knee,None,Full Participation in Practice,NaT
52,2009.0,REG,DET,1.0,00-0020329,CB,Anthony Henry,Anthony,Henry,None,None,None,Shoulder,None,Full Participation in Practice,NaT
71,2009.0,REG,IND,1.0,00-0023464,CB,Marlin Jackson,Marlin,Jackson,None,None,None,Not Injury Related,None,Did Not Participate In Practice,NaT
72,2009.0,REG,IND,1.0,00-0024277,CB,Tim Jennings,Tim,Jennings,None,None,None,Not Injury Related,None,Full Participation in Practice,NaT
80,2009.0,REG,KC,1.0,00-0025701,RB,Jackie Battle,Jackie,Battle,None,None,None,Illness,None,Full Participation in Practice,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6206,2024.0,SB,PHI,22.0,00-0037002,G,Landon Dickerson,Landon,Dickerson,None,None,None,Knee,None,Full Participation in Practice,2025-02-07 20:29:05
6207,2024.0,SB,PHI,22.0,00-0036919,RB,Kenneth Gainwell,Kenneth,Gainwell,None,None,None,Concussion,Knee,Full Participation in Practice,2025-02-07 20:29:05
6208,2024.0,SB,PHI,22.0,00-0034351,TE,Dallas Goedert,Dallas,Goedert,None,None,None,Ankle,None,Full Participation in Practice,2025-02-07 20:29:05
6209,2024.0,SB,PHI,22.0,00-0038112,G,Cam Jurgens,Cam,Jurgens,None,None,None,Back,None,Full Participation in Practice,2025-02-07 20:29:05
6210,2024.0,SB,PHI,22.0,00-0036912,WR,DeVonta Smith,DeVonta,Smith,None,None,None,Hamstring,None,Limited Participation in Practice,2025-02-07 20:29:05

In [17]:
# Take a look at players who were out but participated in practice

injuries[(injuries['report_status'] == 'Out') & (injuries['practice_status'] != 'Did Not Participate In Practice')]

,season,game_type,team,week,gsis_id,position,full_name,first_name,last_name,report_primary_injury,report_secondary_injury,report_status,practice_primary_injury,practice_secondary_injury,practice_status,date_modified
25,2009.0,REG,CIN,1.0,00-0025532,CB,David Jones,David,Jones,Foot,None,Out,Foot,None,Out (Definitely Will Not Play),NaT
26,2009.0,REG,CIN,1.0,00-0026982,T,Andre Smith,Andre,Smith,Foot,None,Out,Foot,None,Out (Definitely Will Not Play),NaT
31,2009.0,REG,CLE,1.0,00-0022905,G,Rex Hadnot,Rex,Hadnot,Knee,None,Out,Knee,None,Out (Definitely Will Not Play),NaT
67,2009.0,REG,HOU,1.0,00-0022767,CB,Jacques Reeves,Jacques,Reeves,Fibula,None,Out,Fibula,None,Full Participation in Practice,NaT
115,2009.0,REG,OAK,1.0,00-0026366,WR,Chaz Schilens,Chaz,Schilens,Foot,None,Out,Foot,None,Out (Definitely Will Not Play),NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6125,2024.0,DIV,LA,20.0,00-0035617,LB,Troy Reeder,Troy,Reeder,Hamstring,None,Out,Hamstring,None,Full Participation in Practice,2025-01-17 20:56:08
6137,2024.0,DIV,PHI,20.0,00-0038978,DT,Byron Young,Byron,Young,Hamstring,None,Out,Hamstring,None,Full Participation in Practice,2025-01-17 20:10:19
6179,2024.0,CON,PHI,21.0,00-0038978,DT,Byron Young,Byron,Young,Hamstring,None,Out,Hamstring,None,Full Participation in Practice,2025-01-24 19:56:53
6180,2024.0,CON,PHI,21.0,00-0037132,WR,Britain Covey,Britain,Covey,Neck,None,Out,Neck,None,Limited Participation in Practice,2025-01-24 19:56:14
6211,2024.0,SB,PHI,22.0,00-0037132,WR,Britain Covey,Britain,Covey,Neck,None,Out,Neck,None,Full Participation in Practice,2025-02-07 20:32:07

In [18]:
# Import rosters

rosters_seas = nfl.import_seasonal_rosters(range(2009, 2025))

In [19]:
# rosters head check

rosters_seas.head()

,season,team,position,depth_chart_position,jersey_number,status,player_name,first_name,last_name,birth_date,...,status_description_abbr,football_name,esb_id,gsis_it_id,smart_id,entry_year,rookie_year,draft_club,draft_number,age
0,2009,DAL,T,None,76,ACT,Flozell Adams,Flozell,Adams,1975-05-18,...,A01,Flozell,ADA280969,None,32004144-4128-0969-9390-de3ae33872eb,1998.0,1998.0,DAL,38,34.0
1,2009,PHI,K,None,2,ACT,David Akers,David,Akers,1974-12-09,...,A01,David,AKE551610,None,3200414b-4555-1610-e0e6-a72c82e419e7,1997.0,1997.0,None,None,34.0
2,2009,WAS,LS,None,67,ACT,Ethan Albright,Lawrence,Albright,1971-05-01,...,A01,Ethan,ALB637766,None,3200414c-4263-7766-3ff2-577dbeb62e1c,1994.0,1994.0,None,None,38.0
3,2009,BLT,ILB,None,51,RES,Brendon Ayanbadejo,Brendon,Ayanbadejo,1976-09-06,...,A01,Brendon,AYA436705,None,32004159-4143-6705-e019-7daf37d2f1af,1999.0,1999.0,None,None,32.0
4,2009,DEN,CB,None,24,ACT,Champ Bailey,Roland,Bailey,1978-06-22,...,A01,Champ,BAI582194,None,32004241-4958-2194-25da-8624608fa14d,1999.0,1999.0,WAS,7,31.0

In [20]:
# Rosters info check

rosters_seas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42809 entries, 0 to 42821
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   season                   42809 non-null  int32
 1   team                     42809 non-null  object
 2   position                 42793 non-null  object
 3   depth_chart_position     27846 non-null  object
 4   jersey_number            42575 non-null  object
 5   status                   42791 non-null  object
 6   player_name              42808 non-null  object
 7   first_name               42809 non-null  object
 8   last_name                42809 non-null  object
 9   birth_date               40232 non-null  datetime64[ns]
 10  height                   42788 non-null  float64
 11  weight                   42792 non-null  float64
 12  college                  35033 non-null  object
 13  player_id                42809 non-null  object
 14  espn_id                  22929 non-null  object
 15  sportradar_id            23660 non-null  object
 16  yahoo_id                 22004 non-null  object
 17  rotowire_id              23702 non-null  object
 18  pff_id                   21547 non-null  object
 19  pfr_id                   16960 non-null  object
 20  fantasy_data_id          20426 non-null  object
 21  sleeper_id               23164 non-null  object
 22  years_exp                42280 non-null  float64
 23  headshot_url             41322 non-null  object
 24  ngs_position             10700 non-null  object
 25  week                     42809 non-null  int32
 26  game_type                42809 non-null  object
 27  status_description_abbr  36658 non-null  object
 28  football_name            42789 non-null  object
 29  esb_id                   42762 non-null  object
 30  gsis_it_id               35315 non-null  object
 31  smart_id                 42680 non-null  object
 32  entry_year               42280 non-null  float64
 33  rookie_year              42267 non-null  float64
 34  draft_club               25671 non-null  object
 35  draft_number             23444 non-null  object
 36  age                      40232 non-null  float64
dtypes: datetime64[ns](1), float64(6), int32(2), object(28)
memory usage: 12.1+ MB

In [21]:
# Take a deeper look at missing bdays

missing = rosters_seas[rosters_seas['birth_date'].isna()]

In [25]:
# How many missing bdays

missing.shape[0]

2577

In [9]:
# Look at roster status types

rosters_seas['status'].value_counts()

ACT    25633
RES     5015
CUT     4115
DEV     3268
INA     1063
UFA      124
RSN       80
RET       76
NWT       62
SUS       54
PUP       35
TRC       15
RSR       10
EXE       10
TRD        9
RFA        3
TRT        3
E14        1
Name: status, dtype: int64

**Found data dictionary outlining status type definitions**

In [26]:
# Take a look at players on IR

rosters_seas[rosters_seas['status'] == 'RES']

,season,team,position,depth_chart_position,jersey_number,status,player_name,first_name,last_name,birth_date,...,status_description_abbr,football_name,esb_id,gsis_it_id,smart_id,entry_year,rookie_year,draft_club,draft_number,age
3,2009,BLT,ILB,None,51,RES,Brendon Ayanbadejo,Brendon,Ayanbadejo,1976-09-06,...,A01,Brendon,AYA436705,None,32004159-4143-6705-e019-7daf37d2f1af,1999.0,1999.0,None,None,32.0
6,2009,CLV,ILB,None,50,RES,Eric Barton,Eric,Barton,1977-09-29,...,A01,Eric,BAR766216,None,32004241-5276-6216-1360-96908316eed6,1999.0,1999.0,OAK,146,31.0
29,2009,CAR,QB,None,17,RES,Jake Delhomme,Jake,Delhomme,1975-01-10,...,I01,Jake,DEL367367,None,32004445-4c36-7367-f75e-2e1555e1a440,1997.0,1997.0,None,None,34.0
41,2009,MIA,NT,None,95,RES,Jason Ferguson,Jason,Ferguson,1974-11-28,...,A01,Jason,FER162060,None,32004645-5216-2060-ec42-a45bc9746a28,1997.0,1997.0,NYJ,229,34.0
43,2009,ATL,WR,None,86,RES,Brian Finneran,Brian,Finneran,1976-01-31,...,A01,Brian,FIN583520,None,32004649-4e58-3520-402c-d27b0be70001,1998.0,1998.0,None,None,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42776,2024,NE,WR,WR,1.0,RES,Ja'Lynn Polk,Ja'Lynn,Polk,2001-04-11,...,R01,Ja'Lynn,POL136646,57158,3200504f-4c13-6646-64f9-3598ba01ba77,2024.0,2024.0,NE,37.0,23.0
42790,2024,ARI,RB,RB,33.0,RES,Trey Benson,Trey,Benson,2002-07-23,...,R01,Trey,BEN649191,57187,32004245-4e64-9191-567b-28b29177bf93,2024.0,2024.0,ARI,66.0,22.0
42791,2024,MIN,QB,QB,9.0,RES,J.J. McCarthy,Jonathan,McCarthy,2003-01-20,...,R01,J.J.,MCC189531,57131,32004d43-4318-9531-b3f5-120a14383239,2024.0,2024.0,MIN,10.0,21.0
42796,2024,BUF,OL,T,67.0,RES,Travis Clayton,Travis,Clayton,2001-02-17,...,R01,Travis,CLA826931,57341,3200434c-4182-6931-55e8-0b9b4cf80da4,2024.0,2024.0,BUF,221.0,23.0
42821,2024,NO,DL,DT,76.0,RES,Camron Peterson,Camron,Peterson,1999-09-13,...,R01,Camron,PAT382575,58061,32005041-5438-2575-6a39-c3744d58b516,2024.0,2024.0,None,NaN,24.0

In [28]:
# Will look at weekly roster info for one year just to explore this particular dataset

roster_weekly = nfl.import_weekly_rosters([2024])

In [29]:
# Weekly info check

roster_weekly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46579 entries, 0 to 46578
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   season                   46579 non-null  int32
 1   team                     46579 non-null  object
 2   position                 46579 non-null  object
 3   depth_chart_position     46579 non-null  object
 4   jersey_number            46534 non-null  float64
 5   status                   46579 non-null  object
 6   player_name              46579 non-null  object
 7   first_name               46579 non-null  object
 8   last_name                46579 non-null  object
 9   birth_date               46520 non-null  datetime64[ns]
 10  height                   46571 non-null  float64
 11  weight                   46579 non-null  int32
 12  college                  46571 non-null  object
 13  player_id                46572 non-null  object
 14  espn_id                  32641 non-null  object
 15  sportradar_id            32678 non-null  object
 16  yahoo_id                 29066 non-null  object
 17  rotowire_id              32678 non-null  object
 18  pff_id                   18244 non-null  object
 19  pfr_id                   28499 non-null  object
 20  fantasy_data_id          15512 non-null  object
 21  sleeper_id               32678 non-null  object
 22  years_exp                46579 non-null  int32
 23  headshot_url             46204 non-null  object
 24  ngs_position             21594 non-null  object
 25  week                     46579 non-null  int32
 26  game_type                46579 non-null  object
 27  status_description_abbr  46579 non-null  object
 28  football_name            46579 non-null  object
 29  esb_id                   46542 non-null  object
 30  gsis_it_id               46579 non-null  object
 31  smart_id                 46527 non-null  object
 32  entry_year               46579 non-null  int32
 33  rookie_year              46576 non-null  float64
 34  draft_club               30453 non-null  object
 35  draft_number             30453 non-null  float64
 36  age                      46520 non-null  float64
dtypes: datetime64[ns](1), float64(5), int32(5), object(26)
memory usage: 12.3+ MB

In [30]:
# Look at one teams IR for one week and see what it looks like in news/game logs

roster_weekly[(roster_weekly['team'] == 'SEA') & (roster_weekly['week'] == 1) & (roster_weekly['status'] == 'RES')]

,season,team,position,depth_chart_position,jersey_number,status,player_name,first_name,last_name,birth_date,...,status_description_abbr,football_name,esb_id,gsis_it_id,smart_id,entry_year,rookie_year,draft_club,draft_number,age
14697,2024,SEA,WR,WR,18.0,RES,Marcus Simms,Marcus,Simms,1997-12-18,...,R01,Marcus,SIM340983,49420,32005349-4d34-0983-b125-1c7d4381b552,2019,2019.0,None,NaN,26.724
24386,2024,SEA,DL,DE,49.0,RES,Joshua Onujiogu,Joshua,Onujiogu,1998-03-03,...,R01,Joshua,ONU207645,54827,32004f4e-5520-7645-e297-db9f33425eef,2022,2022.0,None,NaN,26.519
28907,2024,SEA,OL,T,72.0,RES,Abraham Lucas,Abraham,Lucas,1998-10-15,...,R04,Abraham,LUC027057,54537,32004c55-4302-7057-e67b-e5e8accdbf7f,2022,2022.0,SEA,72.0,25.900
32470,2024,SEA,DL,NT,93.0,RES,Cameron Young,Cameron,Young,2000-06-08,...,R04,Cameron,YOU128406,55988,3200594f-5512-8406-fbe2-6ad8024c21b6,2023,2023.0,SEA,123.0,24.252
33183,2024,SEA,DB,SS,32.0,RES,Jerrick Reed II,Jerrick,Reed,2000-08-07,...,R04,Jerrick,REE475048,56063,32005245-4547-5048-80ea-d2c00db95075,2023,2023.0,SEA,198.0,24.088